apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "{YOUR_MASTER_NODE_IP}"
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: "{YOUR_KUBERNETES_VERSION}"
networking:
  podSubnet: "192.168.0.0/16"
apiServer:
  extraArgs:
    authorization-mode: Node,RBAC
controllerManager:
  extraArgs:
    allocate-node-cidrs: "true"
    cluster-cidr: "192.168.0.0/16"
scheduler: {}
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: KubeProxyConfiguration
mode: "ipvs"
